# This should be somewhere in your workflow file
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Add these steps before the build step
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or whatever Node.js version you're using
          
      - name: Install dependencies
        run: npm ci # or npm install
      
      # Now your build step
      - name: Build
        run: npm run build
      
      # The deploy step and other existing steps...
